before_script:
  - git submodule update --init --recursive

new_test:
  script:
    - python build_tests/test.py run-all

normal:
  script:
    - ./build_tests/normal.sh normal

asan:
  script:
    - ./build_tests/normal.sh asan

usan:
  script:
    - ./build_tests/normal.sh usan

debug:
  script:
    - ./build_tests/normal.sh debug

release:
  script:
    - ./build_tests/normal.sh release

analyzer:
  script:
    - make P=analyzer

coverage:
   script:
     - make coverage

tools:
  script:
    - make ctags
    - make ycm
