before_script:
    - git submodule update --init --recursive

normal:
    script:
        - cmake .
        - make
        - ./src/test/ztests
        - cd src/
        - touch main.cpp
        - make
        - ./test/ztests
        - cd test
        - touch test.cpp
        - ./ztests

asan:
    script:
        - cmake -DCLANG_ASAN=ON
        - make
        - ./src/test/ztests

msan:
    script:
        - cmake -DCLANG_MSAN=ON
        - make
        - ./src/test/ztests

usan:
    script:
        - cmake -DCLANG_USAN=ON
        - make
        - ./src/test/ztests

tsan:
    script:
        - cmake -DCLANG_TSAN=ON
        - make
        - ./src/test/ztests
