before_script:
    - git submodule update --init --recursive

normal:
    script:
        - cmake .
        - make
        - ./src/test/ztests
        - cd src/
        - touch main.cpp
        - make
        - ./test/ztests
        - cd test
        - touch test.cpp
        - ./ztests

asan:
    script:
        - cmake .
        - make asan
        - ./src/test/ztests

msan:
    script:
        - cmake .
        - make msan
        - ./src/test/ztests

usan:
    script:
        - cmake .
        - make usan
        - ./src/test/ztests

tsan:
    script:
        - cmake .
        - make tsan
        - ./src/test/ztests
