before_script:
    - git submodule update --init --recursive
    - ./configure

normal:
    script:
        - cd build/normal
        - make test
        - ./src/test/ztests
        - cd ../../src/
        - touch main.cpp
        - cd ../build/normal/src
        - make test
        - cd ../../../src/test
        - touch test.cpp
        - cd ../../build/normal/src/test
        - make test

asan:
    script:
        - cd build/asan
        - make test

msan:
    script:
        - cd build/msan
        - make test

usan:
    script:
        - cd build/usan
        - make test

tsan:
    script:
        - cd build/tsan
        - make test
