before_script:
    - git submodule update --init --recursive

normal:
    script:
        - cmake .
        - make
        - ./src/test/ztests
        - cd src/
        - touch main.cpp
        - make
        - ./test/ztests
        - cd test
        - touch test.cpp
        - ./ztests

asan:
    script:
        - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .
        - make
        - ./src/test/ztests
