before_script:
    - git submodule update --init --recursive
    - ./configure

normal:
    script:
        - cd build/normal
        - make test
        - ./src/test/ztests
        - cd ../../src/
        - touch main.cpp
        - cd ../build/normal/src
        - make test
        - cd ../../../src/test
        - touch test.cpp
        - cd ../../build/normal/src/test
        - make test

asan:
    script:
        - make P=asan test

msan:
    script:
        - make P=msan test

usan:
    script:
        - make P=usan test

tsan:
    script:
        - make P=tsan test
