before_script:
    - git submodule update --init --recursive

normal:
    script:
        - make
        - make test
        - cd build/normal
        - ./src/lib1/test/lib1_test
        - cd ../../src/
        - touch main.cpp
        - cd ../build/normal/src/lib1
        - make
        - make test
        - cd ../../../src/lib1/test
        - touch test.cpp
        - cd ../../build/normal/src/lib1/test
        - make
        - make test
        - ./lib1_test

asan:
    script:
        - make P=asan
        - make P=asan test

msan:
    script:
        - make P=msan
        - make P=msan test

usan:
    script:
        - make P=usan
        - make P=usan test

tsan:
    script:
        - make P=tsan
        - make P=tsan test

analyzer:
    script:
        - make P=analyzer
