before_script:
  - git submodule update --init --recursive

stages:
   - build
   - tests
   
new_test:
  script:
    - python build_tests/test.py run-all
  stage: build
normal:
  script:
    - ./build_tests/normal.sh normal
  stage: build
asan:
  script:
    - ./build_tests/normal.sh asan
  stage: build
usan:
  script:
    - ./build_tests/normal.sh usan
  stage: build
debug:
  script:
    - ./build_tests/normal.sh debug
  stage: build
release:
  script:
    - ./build_tests/normal.sh release
  stage: build
analyzer:
  script:
    - make P=analyzer
  stage: build
coverage:
   script:
     - make coverage
   stage: tests
tools:
  script:
    - make ycm
  stage: tests
