before_script:
  - git submodule update --init --recursive

normal:
  script:
    - ./build_tests/normal.sh normal

asan:
  script:
    - ./build_tests/normal.sh asan

usan:
  script:
    - ./build_tests/normal.sh usan

debug:
  script:
    - ./build_tests/normal.sh debug

debug:
  script:
    - ./build_tests/normal.sh release

analyzer:
  script:
    - make P=analyzer
