before_script:
    - git submodule update --init --recursive

normal:
    script:
      - ./build_tests/normal.sh

asan:
    script:
        - make P=asan
        - make P=asan test

msan:
    script:
        - make P=msan
        - make P=msan test

usan:
    script:
        - make P=usan
        - make P=usan test

tsan:
    script:
        - make P=tsan
        - make P=tsan test

analyzer:
    script:
        - make P=analyzer
